config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users,only:[:index, :edit, :update, :destroy]
  resources :groups,only:[:new, :create, :edit, :update] do
    resources :messages,only:[:index, :create]

    namespace :api do
      resources :messages ,only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :user_groups
  has_many :users, through: :user_groups

  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last ).present?
      if last_message.body?
        last_message.body
      else
        '画像が投稿されています'
      end
    else
      "まだメッセージがありません" 
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :body, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages
  has_many :user_groups
  has_many :groups, through: :user_groups
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/concerns/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @groups = Group.new(group_params)
    if @groups.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを更新しました。'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return nil if params[:keyword] == ""
    @users = User.where(['nickname LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end  

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member#chat-group-user-8
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.nickname  

        - group.users.each do |user|
          - if current_user.nickname != user.nickname
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.nickname 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render "messages/side_bar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_main_chat.html.haml
.chatMain
  .chatMain__groupInfo
    .chatMain__groupInfo--left
      = @group.name
      .member-name
        Member:
        - @group.users.each do |user|
          = user.nickname
    .chatMain__groupInfo--right
      = link_to edit_group_path(@group), class:"edit-btn" do
        Edit
        
  .chatMain__messageList
    = render @messages
        

  .chatMain__messageForm
    = form_for [@group, @message] ,html: { class: "messageForm--inputBox" }do |f|
      = f.text_field :body, class: 'inputBox--text', placeholder: 'type a message'
      = f.label :image, class: 'inputBox--imgAttachmentBtn' do
        = icon('fas', 'image', class: 'icon')
        = f.file_field :image, class: 'fileOpen'
      = f.submit 'Send', class: 'inputBox--submitBtn'

app/views/messages/_message.html.haml
.chatMain__messageList--block{data: {message: {id: message.id}}}
  .messageInfo
    .messageInfo--userName  
      = message.user.nickname
    .messageInfo--createdAt 
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .messageText 
    - if message.body.present?
      %p.lower-message__content
        = message.body  
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.sideBar
  .sideBar__userName
    .sideBar__userName--topItem
      .topItem--name
        =current_user.nickname
      .topItem--icon
        =link_to new_group_path, class: "btn new-group_btn" do
          =icon('far', 'edit')
        =link_to edit_user_path(current_user), class: "btn edit-account_btn" do
          =icon("fa", "cog")
  .sideBar__groupList
    - current_user.groups.each do |group|
      .sideBar__groupList--block
        = link_to group_messages_path(group) do
          .groupList--name
            = group.name
          .groupList--message
            = group.show_last_message

app/views/messages/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :nickname
          .field-input
            = f.text_field :nickname, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'